"""rename address

Revision ID: 776ae0f3adf2
Revises: a6dc941cce6e
Create Date: 2026-01-04 18:45:02.105649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '776ae0f3adf2'
down_revision = 'a6dc941cce6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address',  new_column_name='location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
